import React, { Component } from 'react'

export default class Terms extends Component {
    render() {
        return (
            <div className="container">
                <div className="row">
                    <div className="col-md-12">
                        <div className="py-4">
                            <h1 className="display-6">Terms of Service</h1>
                            <p>
                            Welcome to Bhej De India, It’s a logistics service company, we provide one click booking for your logistics needs, if you are use this website or our mobile application, you are agreeing to comply with all the privacy policies and terms and condition of  uses and services we offered  by Bhej de India pvt ltd.
                            In the event of conflict between the term and conditions specified here or with any other documents produced between parties, specified terms and conditions is applied.
                            </p>
                            <h5>FOLLOWING REFERENCES ARE BEING USED HERE</h5>
                            <ul>
                                <li>USER &CONSIGNMENT:  it’s a package, parcels, goods or any other goods being transported through our platform. Which is between the sender (consignor/merchant/customer or any other who is sending their goods using bhejde India) and receiver (consignee/merchant/customer or any other parties on receiving end of product delivery). </li>
                                <li>“You” “your” “consigner”, will be referred to the sender, consignor or consignee of the consignment. </li>
                                <li>DANGEROUS GOODS : As classified by IATA DGR, IMDG CODE, ICAO T.I, ADR, OR ANYOTHER NATIONAL REGULATIONS of Transport, will be considered dangerous to Transport with or without approval with bhejde India mobile or website.</li>
                                <li>Bhej de, we, us, our, bhejde India, will be referred to Bhej de Indiapvt ltd (or Owners). Its employees, authorized agent/worker,. It also refers to drivers/ vehicles/owners of vehicles or contractor attached to bhejde Indiapvt ltd to carry or undertake to carry the consignment or perform any service as offered by Bhej De India.</li>
                                <li>Prohibited items which are material/goods/ or consignment which is considered  illegal and prohibited by laws of Republic of India, All laws/statutes/regulations/guidelines/polices/government restrictions/state government restrictions/rules/ bye-laws/ and any kind of notification/decision/ produced by Republic of India/any state government/ministry/department or by board, shall be considered Prohibited with the immediate effect.</li>
                            </ul>
                            <h5>USER OR USERS ELIGIBILITY</h5>
                            <p>USER(S) Means any individual or business owners/business entity/organization that are legally operating in India or in other countries, uses and has the right to use the services provided by Bhej de India. The service provided by Bhej de India is platform based service. Which provides one click booking of SCVs (small commercial vehicles), by customer for one point to other, or for time and usage basis with in the city limits or outside, or intercity, through our platform (mobile application/website).
                            We provide our services to all the business owners/business entities/ or general user who can form a legal binding contracts, under All applicable laws. There for the user or users must not be a minor.
                            Bhej de India is not responsible for the possible consequences caused by your behavior or acts during uses of website/mobile application or services, bhej de India may, in sole discretion, refuse the services to anyone at any point of time.
                            </p>
                            <h5>User OR USERS AGREEMENT</h5>
                            <p>This agreement applies to user(s) if user(s) are visitors, registered - free or paid user(s) who access the web site for any purpose. It also applies to any legal entity which may be represented by you under actual or apparent authority. User(s) may use this site solely for their own personal or internal purposes.
                            This agreement applies to all BHEJ DE INDIA Services offered on the web site, collectively with any additional terms and condition that may be applicable to the specific service used/accessed by user(s).In the event of a conflict or inconsistency between any provision of the terms and conditions mentioned herein with those of the particular service, the provisions of the terms and conditions applicable to such specific Services shall prevail.
                            </p>
                            <h5>AGRIMENT AMENDMENTS FOR USER(S)</h5>
                            <p>BHEJ DE INDIA may change, modify, amend, or update this agreement from time to time with or without any prior notification to user(s) and the amended and restated terms and conditions of use shall be effective immediately on posting. If you do not adhere to the changes, you must stop using the service. Your continuous use of the Services will signify your acceptance of the changed terms. User(s) shall also be bound by any amendment made in any policy or agreement from time to time, referred to in these Terms of Service.</p>
                            <h5>TERMINATION</h5>
                            <p>Most content and some of the features on the web site are made available to visitors free of charge. However, BHEJ DE INDIA reserves the right to terminate access to certain areas or features of the web site at any time for any reason, with or without notice. BHEJ DE INDIA also reserves the universal right to deny access to particular users to any/all of its Services without any prior notice/explanation in order to protect the interests of BHEJ DE INDIA and/or other visitors to the web site. BHEJ DE INDIA reserves the right to limit, deny or create different access to the web site and its features with respect to different user(s), or to change any of the features or introduce new features without prior notice.</p>
                            <h1 className="display-6">TERM AND CONDITION OF USES</h1>
                            <p>The following Terms & Conditions shall apply to customers utilizing the Services offered by the Company for the hiring of vehicles:
                            The customer shall pay the fare (as agreed), parking charges, additional night surcharge (where applicable) and any fee or levy presently payable or hereinafter imposed by the Applicable Law or required to be paid for availing the Services of BHEJ DE INDIA.
                            The customer agrees and accepts that the use of the Services provided by the Company is at the sole risk of the Customer, and further acknowledges that the Company disclaims all representations and warranties of any kind, whether express or implied.
                            The customer shall ensure that he/she will not indulge in any of the following activities while availing the service:
                            </p>
                            <ul>
                                <li>Soiling or damaging the body and/or any other interiors of the vehicles.</li>
                                <li>Misusing, soiling or damaging any of the devices (technical/non-technical) in the vehicle.</li>
                                <li>Asking the driver to break any Traffic/RTO/City Police and/or government rules for any purpose. The driver has the right to refuse such a request by the customer. The driver also has the right to refuse such a pick-up.</li>
                                <li>Pressurizing the driver to overload truck with the consignment than the allowed limit.</li>
                                <li>Only ground floor to ground floor loading unloading is allowed</li>
                                <li>Distance between loading and unloading site must not be more then 30mts</li>
                                <li>Labor charges to be paid by customer. Labor charges will be reflected in your invoice or bill.</li>
                                <li>Driver may ask you add more labor as per weight or size of consignment, extra labor cost will be added and to be paid by customer.</li>
                                <li>BHEJ DE INDIA provides third party insurance, and we doesn’t take any responsibilities of damage/theft or misuse of your consignment,</li>
                                <li>Prohibited items being transported with our without knowledge of driver or company is actionable under law, Bhej de India will not be party to any illegal transport made by you.</li>
                                <li>You undertake to us that you shall not permit any other person who has an interest in the consignment to bring a claim or action against us arising out of Carriage even though we may have been negligent or in default and if a claim or action is made you will indemnify us against the consequences of the claim or action and the costs and expenses we incur in defending it.</li>
                                <li>DRIVERS must upload the documents as asked by Bhej de India to be verified, these documents can be used by Bhej de India for internal or external company purposes.</li>
                            </ul>
                            <p>The Customer shall indemnify Company from and against and in respect of any or all liabilities, losses, charges and expenses (including legal fees and costs on a full indemnity basis) claims, demands, actions and proceedings which Company may incur or sustain directly or indirectly from or by any reason of or in relation to the use or proposed use of the Services by the Customer and shall pay such sums on demand on the Company.
                            The Company is hereby authorized to use the location based information provided by any of the telecommunication companies when the Customer uses the mobile phone to make a vehicle booking. The location based information will be used only to facilitate and improve the probability of locating a mini-truck for the Customer.
                            The Company shall be entitled to disclose to all companies within its group, or any government body as so required by the Applicable Law or by directive or request from any government body, the particulars of the Customer in the possession of Company in any way as Company, in its absolute discretion, deems fit or if it considers it in its interests to do so.
                            The Company shall be entitled at any time without giving any reason to terminate the booking of the vehicle done by the Customer. User(s) shall indemnify BHEJ DE INDIA with respect to any expenses incurred with respect to such booking.
                            In case of lost items during the transit, Company will try to locate the items on a "best-effort" basis but is not responsible for the same in case of loss or damage or theft or misappropriation to / of the same. BHEJ DE INDIA aggregates the vehicles for the purposes of providing Services. In the event of loss of any item, User(s) shall not have any right to withhold the payment to be made to BHEJ DE INDIA. Further, in the event any payments from the User to BHEJ DE INDIA are pending for the period prescribed by BHEJ DE INDIA in its respective invoice / statement, BHEJ DE INDIA reserves the right, in accordance with the Applicable Law, to exercise particular lien over the consignment till full payment is made to BHEJ DE INDIA for the Services. Additionally, User(s) will be liable to indemnify BHEJ DE INDIA against any loss, damage or expenses incurred by it due to the custody of the consignment during this period.
                            Any complaint in respect of the Services or the use of the vehicles, the Customer has to inform the Company of the same in writing within 24 hours of using the vehicles or Services of the Company.
                            The Company shall not be liable for any conduct of the drivers of the vehicles. However, the Company encourages you to notify it, of any complaints that you may have against the driver that you may have hired using the Company's Services.
                            The Company shall be entitled to add to, vary or amend any or all these terms and conditions at any time and the Customer shall be bound by such addition, variation or amendment once such addition, variation or amendment are incorporated into these terms and conditions at Company's website at www.BHEJDE.com on the date that Company may indicate that such addition, variation or amendment is to come into effect.
                            All the calls made to the Company's call center are recorded by the Company for quality and training purposes. In the event you place a query on our app/website including any query with respect to our Services, applicable fees or Terms of Service, you hereby expressly agree to consent to receive our responses, whether by way of telephonic calls or electronic mail, to such query and all related information with respect to our Services. For removal of doubts, related information shall include without limitation any marketing and/or commercial information. You understand, agree and acknowledge that such information shall in no event, qualify as unsolicited commercial communication under the Telecom Unsolicited Commercial Communications Regulations, 2007 and/or due to disclosure of such information, our telephone numbers shall not qualify to be registered under the 'National Do Not Call Register' or the 'Private Do Not Call Register' in accordance with the Telecom Unsolicited Commercial Communications Regulations, 2007 or any other Applicable Law.
                            </p>
                            <h5>Cancellation Policy</h5>
                            <p>All cancellations made 5 minutes after driver allocation will incur a cancellation fee of INR. 50/- (Indian Rupees Fifty only). Cancelling TWO bookings in a day after driver allocation will temporarily suspend your account for 24 hours. Figures are subject to change.
                            Toll Charges: In case of a toll on your trip, return toll fare will be charged and to be paid in cash/electronically to drivers.
                            </p>
                            <h5>DISCLAIMER</h5>
                            <p>All vehicles registered with the Company are continuously tracked using mobile technology for security reasons only. It is hereby made expressly clear to you that the Company does not own any vehicle nor it directly or indirectly employ any driver for the vehicles. Vehicles and drivers are all supplied by third parties and the Company disclaims any and all liability(ies) in respect of the drivers and the vehicles alike.
                            The Company have right to use the customer contact information for its own marketing purposes. The Company may send regular SMS updates to the mobile numbers registered with it.
                            The information contained in this website and BHEJ DE INDIA App is for general information purposes only. The information is provided by BHEJ DE INDIA and while we endeavor to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website / App or the information, products, services, or related graphics contained on the website / App for any purpose. Any reliance you place on such information is therefore strictly at your own risk.
                            In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website / App.
                            Through this website / App you are able to link to other websites which are not under the control of BHEJ DE INDIA. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.
                            Every effort is made to keep the portal up and running smoothly. However, BHEJ DE INDIA takes no responsibility for, and will not be liable for, the portal being temporarily unavailable due to technical issues beyond our control.
                            </p>
                            <h5>YOUR ACCEPTANCE OF TERMS AND CONDITIONS</h5>
                            <p>By giving us your consignment you accept our terms and conditions set out in the consignment note and/or the contract of carriage and/or the contract for the performance of other services on behalf of yourself and/or anyone else who has an interest in the consignment or the performance of other Services irrespective of whether you have signed the front of our consignment note or not. Our terms and conditions also cover and can be invoked by anyone we use or sub-contract to collect, transport, deliver your consignment or perform other Services as well as our employees, directors and agents. Only one of our authorised officers may agree to a variation of these terms and conditions in writing. When you give us the consignment with oral or written instructions that conflict with our terms and conditions we shall not be bound by such instructions.</p>
                            <h5>YOUR OBLIGATION</h5>
                            <ul>
                            <li>You warrant, undertake and guarantee to us:</li>
                            <ul>
                                <li>The contents of the consignment (including but not limited to weight and number of items) have been properly described on our consignment note and that the Consignment Note is complete in all respects and the documents as required for the transporting the consignment including invoice, permits are enclosed with the Consignment Note.</li>
                                <li>That the contents of the Consignment are not Prohibited Items and/or are not restricted by the applicable regulations and that you will supply to us any Dangerous Goods declaration that is needed, properly and accurately in accordance with Applicable Law and neither you nor the consignee is a person or organization with whom we or you may not legally trade under Applicable Law.</li>
                                <li>That all statements and information and documents provided by you relating to the Consignment will be true and correct and you acknowledge that in the event that you make untrue or fraudulent statement about the Consignment or any of its contents, you would risk a civil claim and/or criminal prosecution the penalties for which may include forfeiture and sale. You agree to indemnify us and hold us harmless from any claims that may be brought against us or our agents arising from the information provided by you.</li>
                                <li>We are authorized to deliver the goods at the address mentioned on the Consignment Note and without prejudice to the foregoing it is expressly agreed that we shall be conclusively presumed to have delivered the goods in accordance with this contract. We will be sending the delivery confirmation by SMS/e-mails, no-response within 24 hours would be considered as an affirmative to the delivery.</li>
                                <li>You have declared the correct weight of the consignment and you will provide any special equipment we may need to load or unload the consignment on or off our vehicles.</li>
                                <li>When you have asked us to charge the receiver or a third party and the receiver or third party does not pay us you will promptly settle our invoice together with an administration fee in full within 7 days of us sending you the invoice</li>
                                <li>Applicable Law has been complied with by you.</li>
                            </ul>
                            <li>You understand, agree and acknowledge that the Services are not suitable for transportation of valuables like cash, gold, silver, diamond, precious stones, jewels or jewelry, expensive luxury items etc. (“Valuables”). If you handover / load the vehicles with Valuables for transportation, any loss / damage / theft / misappropriation to / of the consignment shall be at your risk and not ours, for the reasons mentioned earlier and without prejudice, we shall not only have the right to explicitly and specifically disclaim any liability and/or responsibility arising/accruing from the damage / loss / theft / misappropriation to/of the consignment or any contents of the consignment, but also the right to claim indemnification from you where we have suffered loss of reputation / goodwill due to your actions of breaching our terms of service.</li>
                            <li>You understand, agree and acknowledge that if the consignment or any contents thereof are of the value exceeding INR 25,000/- (Indian Rupees Twenty-Five Thousand only), you shall get the consignment insured from a General Insurance company operating in India before handing over the consignment for transportation. In absence of adequate insurance to cover loss of goods in transit or in absence of wrong or non-declaration of the consignment details / value, and whether insured or not, the transportation of the consignment shall be entirely at your risk and not ours and we explicitly and specifically disclaim any liability and/or responsibility arising/accruing from the damage / loss / theft / misappropriation or any insurable loss to / of the consignment or any contents of the consignment and you further agree to indemnify us in all those cases where we have suffered loss of reputation / goodwill due to your actions of breaching our terms of service.</li>
                            <li>You agree to indemnify us and hold us harmless from any liabilities we may suffer or any costs, damages or expenses, including legal costs, we incur either to you or to anyone else arising out of you being in breach of any of these warranties, representations and guarantees, even if we inadvertently accept a consignment that contravenes any of your obligations.</li>
                            <li>You certify that all statements and information you provide relating to the transportation of the consignment will be true and correct. You acknowledge that in the event that you make untrue or fraudulent statements about the consignment or any of its contents you risk a civil claim and/or criminal prosecution the penalties for which include forfeiture and sale of your consignment. To the extent that we may voluntarily assist you in completing the required customs and other formalities such assistance will be rendered at your sole risk. You agree to indemnify us and hold us harmless from any claims that may be brought against us arising from the information you provide to us and any costs we will incur regarding this, and pay any administration fee we may charge you for providing the Services described in this condition.</li>
                            <li>The customer agrees and acknowledges that the use of the Services offered by Company is at the sole risk of the customer and that Company disclaims all representations and warranties of any kind, whether express or implied as to condition, suitability, quality, merchantability and fitness for any purposes are excluded to the fullest extent permitted by Applicable Law. Without prejudice to the above, the Company makes no representation or warranties with respect to:</li>
                            <ul>
                                <li>The Services meeting the customer's requirements.</li>
                                <li>The Services will be uninterrupted, timely, secure, or error-free.</li>
                                <li>Any responsibility or liability for any loss or damage, howsoever caused or suffered by the Customer arising out of the use of Services offered by Company or due to the failure of Company to provide Services to the Customer for any reason whatsoever including but not limited to the Customer's non-compliance with the Services' recorded voice instructions, malfunction, partial or total failure of any network terminal, data processing system, computer tele-transmission or telecommunications system or other circumstances whether or not beyond the control of Company or any person or any organization involved in the above mentioned systems.</li>
                                <li>Any liability for any damages of any kind arising from the use of the Service offered by the Company, including, but not limited to direct, indirect, incidental, punitive, and consequential damages.</li>
                                <li>Any additional or extra charges for far off locations & toll charges as well.</li>
                                <li>Any alternate arrangement(s) if the vehicle has not reached due to any reason.</li>
                            </ul>
                            <li>We are not liable if we do not fulfill any obligations towards you at all as a result of:</li>
                            <ul>
                                <li>Circumstances beyond our control such as (but not limited to):</li>
                                <ul>
                                    <li>Acts of god including earthquakes, cyclones, storms, flooding, fire, disease, fog, snow or frost or other natural calamities or disasters</li>
                                    <li>Force majeure including (but not limited to) war, epidemics, pandemics, accidents, acts of public enemies, strikes, embargoes, perils of the air, local disputes or civil commotions.</li>
                                    <li>National or local disruptions in air or ground transportation networks and mechanical problems to modes of transport or machinery.</li>
                                    <li>Latent defects or inherent vice in the contents of the consignment.</li>
                                    <li>Criminal acts of third parties such as theft and arson.</li>
                                </ul>
                            </ul>
                            <li>Your acts or omissions or those of third parties such as:</li>
                            <ul>
                                <li>You being in breach of (or any other party claiming an interest in the consignment causing you to breach) your obligations under these terms and conditions.</li>
                            </ul>
                            <li>The contents of the consignment consisting of any article that is a prohibited item / Dangerous Goods / Valuables even though we may have accepted the consignment by mistake or you have willingly handed it over to us without notifying / informing / declaring to us.</li>
                            </ul>
                        </div>
                    </div>
                </div>
                
            </div>
        )
    }
}
